// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrRP987BAQpB6SNaJmOuSapxYg-zD-amw',
    appId: '1:90779494002:web:cf29a1a52baab2ebeec4eb',
    messagingSenderId: '90779494002',
    projectId: 'commit-andro',
    authDomain: 'commit-andro.firebaseapp.com',
    storageBucket: 'commit-andro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrPH1x5lRP0H3BzTj1lTQ_ZTH39Kr1n8',
    appId: '1:90779494002:android:3d932c5888fcc772eec4eb',
    messagingSenderId: '90779494002',
    projectId: 'commit-andro',
    storageBucket: 'commit-andro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOdjKcxPTfC6H5_KjQfUiMbB-T_T5VxYY',
    appId: '1:90779494002:ios:733bb9e1b19962b7eec4eb',
    messagingSenderId: '90779494002',
    projectId: 'commit-andro',
    storageBucket: 'commit-andro.appspot.com',
    iosClientId: '90779494002-pgn0q25395s2pb4aelptdt6vftsgtd4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.kommit',
  );
}
